CREATE TABLE `stock`.`loan_product`  (
                                         `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
                                         `product_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT '产品名称',
                                         `product_img` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '产品图标',
                                         `min_price` decimal(22, 6) NULL DEFAULT 0.000000 COMMENT '最低金额',
                                         `max_price` decimal(22, 6) NULL DEFAULT 0.000000 COMMENT '最高金额',
                                         `loan_days` int NOT NULL COMMENT '借贷天数',
                                         `interest_free_days` int NOT NULL COMMENT '免息天数',
                                         `loan_daily_rate` decimal(22, 6) NOT NULL DEFAULT 0.000000 COMMENT '贷款每日利息率',
                                         `break_contract_daily_rate` decimal(22, 6) NOT NULL DEFAULT 0.000000 COMMENT '违约每日利息率',
                                         `max_loan_count` int NOT NULL DEFAULT 0 COMMENT '最多可贷款次数',
                                         `interest_settlement_method` tinyint(1) NULL DEFAULT 0 COMMENT '利息结算方式 0：每日余额扣除利息 1：到期还款结清总利息',
                                         `status` tinyint(1) NULL DEFAULT 0 COMMENT '状态：0：启用 1：禁用',
                                         `sort` int NULL DEFAULT NULL COMMENT '排序',
                                         `currency_id` bigint NOT NULL DEFAULT 1 COMMENT '币种id',
                                         `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
                                         `product_name_en` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-英文',
                                         `product_name_tc` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-繁体',
                                         `product_name_de` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-德国',
                                         `product_name_es` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-西班牙',
                                         `product_name_fr` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-法国',
                                         `product_name_idn` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-印度尼西亚',
                                         `product_name_jp` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-日本',
                                         `product_name_ko` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-韩国',
                                         `product_name_my` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-马来西亚',
                                         `product_name_th` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-泰国',
                                         `product_name_vi` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-越南',
                                         `product_name_pt` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-葡萄牙',
                                         `product_name_rus` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-俄语',
                                         `product_name_blr` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-白俄罗斯',
                                         `product_name_ida` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-印度',
                                         `product_name_sa` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-沙特阿拉伯',
                                         `product_name_ar` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-阿拉伯',
                                         `product_name_it` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '产品名称-意大利',
                                         PRIMARY KEY (`id`)
) ENGINE = InnoDB COMMENT = '贷款产品配置';

CREATE TABLE `stock`.`loan_order`  (
                                     `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
                                     `order_code` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '订单号',
                                     `user_id` bigint NOT NULL COMMENT '用户id',
                                     `loan_product_id` bigint NOT NULL COMMENT '贷款产品id',
                                     `order_price` decimal(22, 6) NOT NULL DEFAULT 0.000000 COMMENT '订单金额',
                                     `loan_days` int NOT NULL COMMENT '借贷天数',
                                     `interest_free_days` int NOT NULL COMMENT '免息天数',
                                     `loan_daily_rate` decimal(22, 6) NOT NULL DEFAULT 0.000000 COMMENT '贷款每日利息率',
                                     `break_contract_daily_rate` decimal(22, 6) NOT NULL DEFAULT 0.000000 COMMENT '违约每日利息率',
                                     `create_time` datetime(0) NULL DEFAULT NULL COMMENT '下单时间',
                                     `interest_settlement_method` tinyint(1) NOT NULL DEFAULT 0 COMMENT '利息结算方式 0：每日余额扣除利息 1：到期还款结清总利息',
                                     `order_status` tinyint(1) NULL DEFAULT 0 COMMENT '订单状态：0：待审核  1：进行中 2：已完成 3：已驳回',
                                     `currency_id` bigint NOT NULL DEFAULT 3 COMMENT '货币id',
                                     `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '更新者',
                                     `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
                                     `sql_version` bigint NULL DEFAULT 0 COMMENT 'sql版本',
                                     `user_info_country` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '国家',
                                     `immediate_family_member_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '直系亲属姓名',
                                     `immediate_family_member_phone_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '直系亲属电话号码',
                                     `residential_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '居住地址',
                                     `id_type` tinyint(1) NULL DEFAULT 0 COMMENT '证件类型 0：身份证 1：驾驶证 2：护照',
                                     `id_number` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证件号码',
                                     `img1_key` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证件图片（正面）',
                                     `img2_key` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证件图片（背面）',
                                     `img3_key` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证件图片（手持）',
                                     `img4_key` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '银行流水清单',
                                     PRIMARY KEY (`id`),
                                     INDEX `user_id`(`user_id`, `order_status`) USING BTREE
) ENGINE = InnoDB COMMENT = '贷款订单';